//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string Logo { get; set; }
    }
}
