//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListMail
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Block { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Num { get; set; }
    }
}
