//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SM.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is Required.
        /// </summary>
        public static string AgeRequiredError {
            get {
                return ResourceManager.GetString("AgeRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a demo page.
        /// </summary>
        public static string DisplayString {
            get {
                return ResourceManager.GetString("DisplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Upload File.
        /// </summary>
        public static string FormUpload {
            get {
                return ResourceManager.GetString("FormUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string FromUpload {
            get {
                return ResourceManager.GetString("FromUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới và Cập nhật nếu tồn tại.
        /// </summary>
        public static string Import_AddUpdate {
            get {
                return ResourceManager.GetString("Import_AddUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ tạo mới.
        /// </summary>
        public static string Import_OnlyAdd {
            get {
                return ResourceManager.GetString("Import_OnlyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nếu tồn tại.
        /// </summary>
        public static string Import_OnlyInactive {
            get {
                return ResourceManager.GetString("Import_OnlyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ cập nhật nếu tồn tại.
        /// </summary>
        public static string Import_OnlyUpdate {
            get {
                return ResourceManager.GetString("Import_OnlyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string NameRequiredError {
            get {
                return ResourceManager.GetString("NameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectFile.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Application.
        /// </summary>
        public static string SiteHeader {
            get {
                return ResourceManager.GetString("SiteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Tỉnh Thành.
        /// </summary>
        public static string TitleProvince {
            get {
                return ResourceManager.GetString("TitleProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form upload.
        /// </summary>
        public static string TitleUpload {
            get {
                return ResourceManager.GetString("TitleUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
    }
}
